<!DOCTYPE html>
<html>
<body>
    <table>
      <tr>
        <td>アカウント名：</td>
        <td>{{.account}}</td>
      </tr>
      <tr>
        <td>お名前：</td>
        <td>{{.name}}</td>
      </tr>
      <tr>
        <td>パスワード：</td>
        <td>{{.passwd}}</td>
      </tr>
    </table>
</body>
</html>
